module.exports = [
  'Afghan',        'African',        'American',
  'Andhra',         'Arabian',       'Asian',          'Assamese',
  'Awadhi',         'BBQ',           'Bakery',         'Bangladeshi',
  'Bar Food',       'Belgian',       'Bengali',        'Beverages',
  'Bihari',         'Biryani',       'Bohri',          'Brazilian',
  'British',        'Bubble Tea',    'Burger',         'Burmese',
  'Cafe',           'Cafe Food',     'Cantonese',      'Charcoal Chicken',
  'Chettinad',      'Chinese',       'Coffee',         'Continental',
  'Cuisine Varies', 'Desserts',      'Drinks Only',    'Egyptian',
  'Ethiopian',      'European',      'Falafel',        'Fast Food',
  'Finger Food',    'French',        'Frozen Yogurt',  'Fusion',
  'German',         'Goan',          'Greek',          'Gujarati',
  'Healthy Food',   'Hot dogs',      'Hyderabadi',     'Ice Cream',
  'Indian',         'Indonesian',    'International',  'Iranian',
  'Irish',          'Israeli',       'Italian',        'Japanese',
  'Juices',         'Kashmiri',      'Kebab',          'Kerala',
  'Konkan',         'Korean',        'Lebanese',       'Lucknowi',
  'Maharashtrian',  'Malaysian',     'Malwani',        'Mangalorean',
  'Mediterranean',  'Mexican',       'Middle Eastern', 'Mishti',
  'Mithai',         'Modern Indian', 'Momos',          'Mongolian',
  'Moroccan',       'Mughlai',       'Naga',           'Nepalese',
  'North Eastern',  'North Indian',  'Odia',           'Oriental',
  'Paan',           'Pakistani',     'Pan Asian',      'Panini',
  'Parsi',          'Pizza',         'Poké',           'Portuguese',
  'Rajasthani',     'Raw Meats',     'Roast Chicken',  'Rolls'
]